server.port=15001

spring.application.name=BookManager


# h2 config
# ===============================
# پیکربندی اتصال به H2
# ===============================

# تعیین درایور
#spring.datasource.driver-class-name=org.h2.Driver
#
## آدرس اتصال (در اینجا حالت In-Memory با نام 'mydb')
#spring.datasource.url=jdbc:h2:mem:bookstore
#
## نام کاربری و رمز عبور (پیش‌فرض H2)
#spring.datasource.username=sa
#spring.datasource.password=

# ===============================
# پیکربندی Hibernate / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ===============================
# فعال‌سازی کنسول وب H2 (برای دیدن دیتابیس در مرورگر)
# ===============================
spring.h2.console.enabled=true



spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-message=always


#spring.mongodb.uri=mongodb://admin:pass123@mongo:27017/learning_db?authSource=admin

spring.mongodb.uri=mongodb://admin:pass123@localhost:27017/bookStore?authSource=admin


