### add book bt

POST http://localhost:15001/book
Content-Type: application/json

{
  "title":"کتاب خوب",
  "author":"بنده خدا",
  "price":100.01,
  "description":"یه کتاب"
}

### find book by id

GET http://localhost:15001/books/1


### add book in mongo

POST http://localhost:15001/api/v1/books
Content-Type: application/json

{
  "title":"2 کتاب خوب",
  "author":"بنده خدا",
  "price":100.01,
  "description":"یه کتاب"
}